name: Flow CMS - REST API
addr: 0.0.0.0:3000
log_level: debug
request_logging: true
compress_response: true
redirect_slashes: true
panic_recover: true
no_cache: true
cors:
  allowed_origins: 
    - "*"
  allowed_methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers: 
    - Accept
    - Authorization
    - Content-Type
    - X-CSRF-Token
  exposed_headers: 
    - Link
  allow_credentials: true
  max_age: 300
migrations_path: migrations
default_connection: default
connection_strings:
  default:
    url: {{env "DB_URL"}}
    dialect: "mysql"
    #database: "flow_dev"
    #host: "localhost"
    #port: "3306"
    #user: "root"
    #password: "root"
    #pool: 0
    #idle_pool: 0
    #options: 
    #  key: value
  
app_settings:
  jwt_secret: {{env "JWT_SECRET"}}