name: Flow CMS - REST API
request_logging: true
compress_response: true
redirect_slashes: true
panic_recover: true
cors:
  allowed_origins: 
    - "*"
  allowed_methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers: 
    - Accept
    - Authorization
    - Content-Type
    - X-CSRF-Token
  exposed_headers: 
    - Link
  allow_credentials: true
  max_age: 300

db:
  url: {{envOr "DB_URL", "mysql://root:root@(localhost:3306)/flow_db?parseTime=true&multiStatements=true&readTimeout=1s"}}
  dialect: "mysql"
  database: "flow_dev"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  Pool: 0
  IdlePool: 0
  Options: 
    key: value
  
app_settings:
  GitHubClientID: 8d5d88778095720834ba
  GitHubClientSecret: 2866d395cbdeb55591831e2b4fa5bc66e22f160d
  GitHubOrganization: SwipeStoxGmbH
  GitHubTeam: "Core"